---
title: "Bird_Study"
author: "Cindy Tribuzio"
date: "7/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(rvest)
library(readr)
library(dplyr)
library(janitor)
library(ggplot2)
library(scales)
```
```{r}
webpage <- read_html("https://www.pwrc.usgs.gov/bbl/manual/speclist.cfm")

tbls <- html_nodes(webpage, "table") %>% 
    html_table(fill = TRUE)

species <- tbls[[1]] %>% 
    clean_names() %>% 
    select(alpha_code, common_name) %>% 
    mutate(alpha_code = tolower(alpha_code))
```

# Read in data files
```{r}
pred <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A9ffec04c-7e2d-41dd-9e88-b6c2e8c4375e")

nest <- read_csv("https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A982bd2fc-4edf-4da7-96ef-0d11b853102d")

```

# Function for converting/adding species common names
```{r}
spc2cmmn <- function (df, species){
  return_df <- left_join(df, species, by = c("species" = "alpha_code"))
}
```

# Calculate total number of predators by year and species (using common name) and plot
```{r}
pred2 <- spc2cmmn(pred,species)
head(pred2)

pred_tot<-pred2 %>% 
  group_by(year, common_name) %>% 
  summarize(pred_count = sum(count,na.rm=T)) %>% 
  filter(!is.na(common_name))
head(pred_tot)

ggplot(pred_tot,aes(x=year,y=pred_count,color=common_name))+
  geom_line()+
  geom_point()+
  facet_grid(common_name~.,scales="free_y")+
  scale_y_continuous(breaks = breaks_pretty(n=2))+
  labs(x="Year",y="Count",title="Predator Counts")+
  theme_bw()+
  theme(
    strip.text=element_blank()
  )
```

# Calculate total number of eggs predated by year and species common name
```{r}
nest2 <- spc2cmmn(nest,species)
head(nest2)

egg_tot<- nest2 %>% 
  group_by(year, common_name) %>% 
  summarize(egg_pred_ct = sum(number_eggs_predated)) %>% 
  filter(!is.na(common_name))
head(egg_tot)
```

# Calculate total number of predators by year, join to summarized egg predation table, and plot results
```{r}
spc_summ <- left_join()
```


