---
title: "Cindy's Research"
author: "Cindy Tribuzio"
date: "7/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
Hi, I'm Cindy!

# Links

* [RMarkdown Intro](R/rmarkdown-intro.html)

```{r}
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
  library(scales) # install.packages("scales")
  library(patchwork)
```

```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv"),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"))
        return(esc)
    }
)

head(esc)
```

```{r}
annual_esc <- esc %>% 
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarize(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink"))
head(annual_esc)
```
```{r}
ggplot(annual_esc, aes(x = Species, y = escapement, fill=SASAP.Region)) +
  geom_col()
```
```{r}
my_theme <- theme_bw()+
  theme(legend.position = "bottom")
kodiak <- annual_esc %>% 
  filter(SASAP.Region == "Kodiak")
p1<-ggplot(kodiak, aes(x = Year, y = escapement, color = Species))+
  geom_line()+
  geom_point()+
  scale_y_continuous(labels = comma)+
  labs(x="Year",y="Escapment (#s)", title = "Kodiak Salmon Escapment")+
  my_theme

ggsave("Figures/kodiak_esc.png")
  
```
```{r}
ggplot(annual_esc, aes(x=Year,y=escapement,color=Species))+
  geom_line()+
  geom_point()+
  scale_y_continuous(labels = comma)+
  facet_wrap(~SASAP.Region,scales = "free_y")+
  labs(x="Year",y="Escapment (#s)", title = "Kodiak Salmon Escapment")+
  my_theme
```

```{r}
p2 <- ggplot(annual_esc,mapping=aes(x=Species,y=escapement, fill = Year))+
  geom_col()+
  my_theme

p3 <- ggplot(annual_esc,mapping=aes(x=Species,y=escapement, fill = SASAP.Region))+
  geom_col()+
  my_theme
(p2 | p3)/p1
```

```{r}
locations <- esc %>% 
  distinct(Location, Longitude, Latitude) %>% 
  drop_na()
datatable(locations)
```
```{r}
leaflet(locations) %>% 
  addTiles() %>% 
  addMarkers(lng = ~Longitude, lat = ~Latitude, popup = ~ Location)
```
  
```{r}
leaflet(locations) %>% 
  addWMSTiles("https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv?",
              layers = 'GEBCO_LATEST',
              attribution = "Imagery reproduced from the GEBCO_2014 Grid, version 20150318, www.gebco.net") %>%
  addCircleMarkers(lng = ~Longitude,
                   lat = ~Latitude,
                   popup = ~ Location,
                   radius = 5,
                   # set fill properties
                   fillColor = "salmon",
                   fillOpacity = 1,
                   # set stroke properties
                   stroke = T,
                   weight = 0.5,
                   color = "white",
                   opacity = 1)
```
  
  