---
title: "Session 8"
author: "Cindy Tribuzio"
date: "7/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(readr)
```

# Data Sources
Data from ADFG https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1
```{r}
catch_original <- read_csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1")
```

# Clean and reshape data
  # Remove unnecessary columns
```{r}
catch_data <- catch_original %>% 
  select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)

head(catch_data)

```
This will do the same thing

```{r}
catch_data <- catch_original %>% 
  select(-All, -notesRegCode)

head(catch_data)  
```
  
  
  # check column type
```{r}
glimpse(catch_data)

catch_clean <- catch_data %>% 
  mutate(Chinook = if_else(Chinook == "I", 1, as.numeric(Chinook)))

head(catch_clean)
```
 
  # Reshape data
```{r}
catch_long <- catch_clean %>% 
  pivot_longer(cols = -c(Region, Year), names_to = "species", values_to = "catch")

head(catch_long)
```
  
```{r}
catch_wide <- catch_long %>% 
  pivot_wider(names_from = species, values_from = catch)

head(catch_wide)
```
  
  # Renaming
  
```{r}
catch_long <- catch_long %>% 
  rename(catch_thousands = catch)

head(catch_long)
```
  # Adding column and removing
```{r}
catch_long <- catch_long %>% 
  mutate(catch = catch_thousands * 1000) %>% 
  select(-catch_thousands)

head(catch_long)
```

  #Summary 
  
```{r}
n_region <- catch_long %>% 
  group_by(Region) %>%
  summarize(n = n())

head(n_region)
```
  
# Putting it all together in short code
```{r}
catch_original <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"))
region_defs <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.303.1", method = "libcurl")) %>% 
    select(code, mgmtArea)

mean_region <- catch_original %>%
  select(-All, -notesRegCode) %>% 
  mutate(Chinook = ifelse(Chinook == "I", 1, Chinook)) %>% 
  mutate(Chinook = as.numeric(Chinook)) %>% 
  pivot_longer(-c(Region, Year), names_to = "species", values_to = "catch") %>%
  mutate(catch = catch*1000) %>% 
  group_by(Region) %>% 
  summarize(mean_catch = mean(catch)) %>% 
  left_join(region_defs, by = c("Region" = "code"))

head(mean_region)
```

  